#ifndef SEESAW_DEVICE_CONFIG_H
#define SEESAW_DEVICE_CONFIG_H

#define PRODUCT_CODE 4600

#define CONFIG_NO_ADDR
#define CONFIG_NO_ACTIVITY_LED
#define CONFIG_NO_EEPROM

//* ================ POOL SIZES =================== *//
#define EVT_SIZE_SMALL 32
#define EVT_SIZE_MEDIUM 64
#define EVT_SIZE_LARGE 256
#define EVT_COUNT_SMALL 128
#define EVT_COUNT_MEDIUM 64
#define EVT_COUNT_LARGE 8

//* ================ ADC =================== *//
#define CONFIG_ADC 1

#define CONFIG_ADC_INPUT_0 1
#define CONFIG_ADC_INPUT_0_PIN 2

#define CONFIG_ADC_INPUT_1 1
#define CONFIG_ADC_INPUT_1_PIN 3

#define CONFIG_ADC_INPUT_2 1
#define CONFIG_ADC_INPUT_2_PIN 4

#define CONFIG_ADC_INPUT_3 1
#define CONFIG_ADC_INPUT_3_PIN 5

#define CONFIG_ADC_INPUT_4 1
#define CONFIG_ADC_INPUT_4_PIN 6

#define CONFIG_ADC_INPUT_5 1
#define CONFIG_ADC_INPUT_5_PIN 7

#define CONFIG_ADC_INPUT_6 1
#define CONFIG_ADC_INPUT_6_PIN 11

#define CONFIG_ADC_INPUT_7 1
#define CONFIG_ADC_INPUT_7_PIN 9

#define CONFIG_ADC_INPUT_8 1
#define CONFIG_ADC_INPUT_8_PIN 10

//* ================ DAC =================== *//
#define CONFIG_DAC 0

//* ================ TOUCH =================== *//
#define CONFIG_TOUCH 0

//* ================ TIMER ==================== *//
#define CONFIG_TIMER 1

// A2
#define CONFIG_TIMER_PWM_OUT0 1
#define CONFIG_TIMER_PWM_OUT0_IS_TCC
#define CONFIG_TIMER_PWM_OUT0_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT0_TCC TCC0
#define CONFIG_TIMER_PWM_OUT0_WO 0
#define CONFIG_TIMER_PWM_OUT0_PIN 4

// A3
#define CONFIG_TIMER_PWM_OUT1 1
#define CONFIG_TIMER_PWM_OUT1_IS_TCC
#define CONFIG_TIMER_PWM_OUT1_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT1_TCC TCC0
#define CONFIG_TIMER_PWM_OUT1_WO 1
#define CONFIG_TIMER_PWM_OUT1_PIN 5

// TX
#define CONFIG_TIMER_PWM_OUT2 1
#define CONFIG_TIMER_PWM_OUT2_IS_TCC
#define CONFIG_TIMER_PWM_OUT2_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT2_TCC TCC1
#define CONFIG_TIMER_PWM_OUT2_WO 0
#define CONFIG_TIMER_PWM_OUT2_PIN 6

// RX
#define CONFIG_TIMER_PWM_OUT3 1
#define CONFIG_TIMER_PWM_OUT3_IS_TCC
#define CONFIG_TIMER_PWM_OUT3_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT3_TCC TCC1
#define CONFIG_TIMER_PWM_OUT3_WO 1
#define CONFIG_TIMER_PWM_OUT3_PIN 7

// SCK
#define CONFIG_TIMER_PWM_OUT4 1
#define CONFIG_TIMER_PWM_OUT4_IS_TCC
#define CONFIG_TIMER_PWM_OUT4_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT4_TCC TCC0
#define CONFIG_TIMER_PWM_OUT4_WO 3
#define CONFIG_TIMER_PWM_OUT4_PIN 11

// MI
#define CONFIG_TIMER_PWM_OUT5 1
#define CONFIG_TIMER_PWM_OUT5_IS_TCC
#define CONFIG_TIMER_PWM_OUT5_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT5_TCC TCC1
#define CONFIG_TIMER_PWM_OUT5_WO 3
#define CONFIG_TIMER_PWM_OUT5_PIN 9

// MO
#define CONFIG_TIMER_PWM_OUT6 1
#define CONFIG_TIMER_PWM_OUT6_IS_TCC
#define CONFIG_TIMER_PWM_OUT6_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT6_TCC TCC0
#define CONFIG_TIMER_PWM_OUT6_WO 2
#define CONFIG_TIMER_PWM_OUT6_PIN 10

#define CONFIG_TIMER_PWM_OUT7 0
#define CONFIG_TIMER_PWM_OUT7_TC TC5
#define CONFIG_TIMER_PWM_OUT7_TCC NOT_ON_TCC
#define CONFIG_TIMER_PWM_OUT7_WO 0
#define CONFIG_TIMER_PWM_OUT7_PIN 0

#define CONFIG_TIMER_PWM_OUT8 0
#define CONFIG_TIMER_PWM_OUT8_TC TC5
#define CONFIG_TIMER_PWM_OUT8_TCC NOT_ON_TCC
#define CONFIG_TIMER_PWM_OUT8_WO 0
#define CONFIG_TIMER_PWM_OUT8_PIN 0

#define CONFIG_TIMER_PWM_OUT9 0
#define CONFIG_TIMER_PWM_OUT9_TC TC5
#define CONFIG_TIMER_PWM_OUT9_TCC NOT_ON_TCC
#define CONFIG_TIMER_PWM_OUT9_WO 0
#define CONFIG_TIMER_PWM_OUT9_PIN 0

#define CONFIG_TIMER_PWM_OUT10 0
#define CONFIG_TIMER_PWM_OUT10_IS_TCC
#define CONFIG_TIMER_PWM_OUT10_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT10_TCC TCC2
#define CONFIG_TIMER_PWM_OUT10_WO 0
#define CONFIG_TIMER_PWM_OUT10_PIN 0

#define CONFIG_TIMER_PWM_OUT11 0
#define CONFIG_TIMER_PWM_OUT11_IS_TCC
#define CONFIG_TIMER_PWM_OUT11_TC NOT_ON_TC
#define CONFIG_TIMER_PWM_OUT11_TCC TCC2
#define CONFIG_TIMER_PWM_OUT11_WO 0
#define CONFIG_TIMER_PWM_OUT11_PIN 0


//* ============== INTERRUPT =================== *//
#define CONFIG_INTERRUPT 0
#define CONFIG_INTERRUPT_PIN 0

//* ============== I2C SLAVE =================== *//
#define CONFIG_I2C_SLAVE 1
#define CONFIG_I2C_SLAVE_SERCOM SERCOM1
#define CONFIG_I2C_SLAVE_HANDLER SERCOM1_Handler
#define CONFIG_I2C_SLAVE_IRQn SERCOM1_IRQn
#define CONFIG_I2C_SLAVE_PIN_SDA 16
#define CONFIG_I2C_SLAVE_PIN_SCL 17
#define CONFIG_I2C_SLAVE_MUX 2
#define CONFIG_I2C_SLAVE_FLOW_CONTROL 1
#define CONFIG_I2C_SLAVE_FLOW_CONTROL_PIN CONFIG_I2C_SLAVE_PIN_SCL
#define CONFIG_I2C_SLAVE_ADDR 0x49

//* ============== SERCOM =================== *//
#define CONFIG_SERCOM0 0
#define CONFIG_SERCOM1 0
#define CONFIG_SERCOM2 0

//These are only available on samd21
#define CONFIG_SERCOM3 0
#define CONFIG_SERCOM4 0
#define CONFIG_SERCOM5 0

//* ============== DAP =================== *//
#define CONFIG_DAP 0

//* =========== NEOPIXEL ================ *//
#define CONFIG_NEOPIXEL 1
#define CONFIG_NEOPIXEL_BUF_MAX 512

//* =========== POWER SENSE ================ *//
#define CONFIG_POWER_SENSE 0

//* =========== USB ================ *//
#define CONFIG_USB 1

#define USB_VID 0x239A
#define USB_PID 0x80CC

#define USB_PRODUCT "QT Py M0 Seesaw"
#define USB_MANUFACTURER "Adafruit Industries LLC"

#endif
